tests:
  script:
    - pip install -r requirements.txt
    - pip install -e .
    - mv .env.development .env
    - nosetests tests
  tags: ["cgc-linter"]

lint:
  script:
    - pip install -r requirements.txt
    - pip install -e .
    - lint.py
  tags: ["cgc-linter"]

docs:
  script: "generate_docs"
  tags: ["cgc-linter"]

build_images:
    only: ["master"]
    stage: deploy
    script:
    - angr-build meister
    tags: ["docker-builder"]
